akuity/terraform-provider-akp

.github/workflows/test.yml
akp/resource_akp_cluster.go
akp/resource_akp_instance.go

Now resource is deleted from state instead of throwing an error

Fix an error when resource is not found

---

akp/data_source_akp_cluster.go
akp/data_source_akp_clusters.go
akp/data_source_akp_instance.go
akp/data_source_akp_instances.go
akp/provider.go
akp/resource_akp_cluster.go
akp/resource_akp_instance.go
akp/types/instance.go
docs/data-sources/cluster.md
go.mod
go.sum

Sync the used API library with the latest one:
* Fix: Getting the manifests now return manifests and not an empty string
* Fix: Argo CD Instance id returns an actual instance id

Akuity API update

---

akp/data_source_akp_instance.go
akp/data_source_akp_instances.go
akp/planmodifiers/list/use_state_null_for_unknown.go
akp/planmodifiers/object/use_state_null_for_unknown.go
akp/resource_akp_cluster.go
akp/resource_akp_instance.go
akp/resource_akp_instance_schema.go
akp/types/banner.go
akp/types/chat.go
akp/types/cluster_customization.go
akp/types/config.go
akp/types/extension.go
akp/types/googleanalytics.go
akp/types/helm.go
akp/types/instance.go
akp/types/ip_allow.go
akp/types/kustomize.go
akp/types/rbac_config.go
akp/types/reposerver_controlplane.go
akp/types/reposerver_delegate.go
akp/types/reposerver_managedcluster.go
akp/types/resource.go
akp/types/spec.go
akp/types/statusbadge.go
akp/types/webterminal.go
docs/data-sources/instance.md
docs/data-sources/instances.md
docs/resources/instance.md

Adds `config`, `rbac_config` and `spec` fields to `akp_instance` resource and data sources

Advanced `akp_instance` management

---

akp/data_source_akp_instance.go
akp/data_source_akp_instances.go
akp/resource_akp_instance.go
akp/resource_akp_instance_schema.go
akp/types/instance.go
akp/types/secrets.go
docs/data-sources/instance.md
docs/data-sources/instances.md
docs/resources/instance.md
examples/resources/akp_instance/resource.tf

Add/edit/remove sso secrets, notification secrets and image updater secrets

Managing secrets

---

akp/provider.go
go.mod
go.sum

We should replace existing gateway client with new [akuity/grpc-gateway-client](https://github.com/akuity/grpc-gateway-client).

Replace gateway client with `grpc-gateway-client`

---

akp/resource_akp_instance_schema.go
akp/types/types.go

fix: conversion error of instance clustercustomization and description

---

akp/resource_akp_instance_schema.go
akp/types/instance.go

fix: show changes after applying

---

docs/resources/cluster.md
examples/resources/akp_cluster/resource.tf

docs: add doc of ignoring the token change in lifecycle

---

docs/resources/instance.md
examples/resources/akp_instance/resource.tf

docs: add documentation for argocd_cm and argocd_ssh_known_hosts_cm

---

docs/resources/cluster.md
docs/resources/instance.md

feat(docs): add bare minimum example resource usage

---

README.md
akp/resource_akp_cluster_test.go
docs/resources/cluster.md
examples/resources/akp_cluster/resource.tf

fix(docs): invalid kustomization examples

---

akp/resource_akp_cluster_schema.go
akp/resource_akp_instance_schema.go

Add ns/name validation to cluster, and name validation to instance

Add validation to cluster and instance

---

akp/types/configmap.go

Fixes https://github.com/akuity/terraform-provider-akp/issues/211

fix: applying fields to the ArgoCD map may result in inconsistent orders

---

.github/workflows/release.yml
akp/data_source_akp_instance_test.go

https://goreleaser.com/deprecations/#-rm-dist

fix: update goreleaser-action@v6 command

---

.goreleaser.yml

ref: https://github.com/goreleaser/goreleaser/issues/4134

feat: configure goreleaser to use semver to sort tags

---

.goreleaser.yml

Reverts akuity/terraform-provider-akp#225

Revert "feat: configure goreleaser to use semver to sort tags"

---

akp/resource_akp_instance.go

Fixes https://github.com/akuity/terraform-provider-akp/issues/254.

fix: instance name cannot be updated correctly

---

.github/workflows/test.yml
akp/resource_akp_cluster.go
go.mod

Fixes https://github.com/akuity/terraform-provider-akp/issues/275

fix: permission denied when checking cluster recon status

---

akp/resource_akp_instance.go
akp/resource_akp_instance_schema.go
akp/types/argocd.go
akp/types/types.go

Fixes https://github.com/akuity/terraform-provider-akp/issues/255

fix: computing instance extensions instead of manual input

---

README.md

Fix the broken link to point the agent to correct URL - https://docs.akuity.io/argo-cd/clusters/

chore: fix the broken link

---

akp/types/types.go

Fixes https://github.com/akuity/terraform-provider-akp/issues/286

fix: do not report autoscalarconfig in tf state if cluster size is not set to auto

---

akp/resource_akp_kargoagent.go

Fixes https://github.com/akuity/terraform-provider-akp/issues/326

fix: kubeconfig not working for kargo agent

---

akp/resource_akp_instance.go
akp/resource_akp_kargo.go
akp/resource_helpers.go

Fixes https://github.com/akuity/terraform-provider-akp/issues/322

fix: akp_instance and akp_kargo_instance completes before the instance becomes really ready

---

akp/data_source_akp_kargo_schema.go
akp/resource_akp_kargo.go
akp/resource_akp_kargo_schema.go
akp/types/kargo_instance.go
docs/data-sources/kargo_instance.md
docs/resources/kargo_instance.md
examples/resources/akp_kargo_instance/kargo-manifests/kargo.yaml
examples/resources/akp_kargo_instance/resource.tf
go.mod
go.sum

Related to https://github.com/akuity/terraform-provider-akp/issues/309.

feat: support applying kargo resources in kargo _instance

---

akp/data_source_akp_instance_schema.go
akp/data_source_akp_instance_test.go
akp/data_source_akp_kargo_test.go
akp/resource_akp_instance.go
akp/resource_akp_instance_schema.go
akp/resource_akp_kargo.go
akp/resource_utils.go
akp/types/instance.go
akp/types/kargo_instance.go
docs/data-sources/instance.md
docs/resources/instance.md
examples/resources/akp_instance/argo-manifests/argo.yaml
examples/resources/akp_instance/resource.tf
go.mod

Related to https://github.com/akuity/terraform-provider-akp/issues/309, support applying argo resources in argo cd instance

feat: support applying argo resources in argo cd instance

---

akp/data_source_akp_instance.go
akp/data_source_akp_kargo.go
akp/resource_akp_instance.go
akp/resource_akp_kargo.go
akp/types/instance.go
akp/types/kargo_instance.go

Fixes https://github.com/akuity/terraform-provider-akp/issues/348

fix: inconsistent result caused by argo/kargo existing resources

---

akp/resource_utils.go

The error will be something like:
```
Error: Invalid Kargo Resource JSON, the input resource should be JSON format and will not be applied
│ 
│   with akp_kargo_instance.example,
│   on test.tf line 23, in resource "akp_kargo_instance" "example":
│   23: resource "akp_kargo_instance" "example" {
│ 
│ Failed to parse JSON for resource key 'aaa': invalid character 'a' looking for beginning of value
│ Resource content: apiVersion: kargo.akuity.io/v1alpha1
│ kind: Project
│ metadata:
│   name: aaa
```

fix: report error when applying argo/kargo resources if the format is not JSON

---

akp/types/types.go

Related to https://github.com/akuity/terraform-provider-akp/issues/374, cluster has issue as well.

fix: cluster deletion not working properly if the cluster has already been deleted
